### PR TITLE
Add Querly to Ruby list

### PR DESCRIPTION
**Pull request by ybiquitous**
Hi!

This adds a linter named [Querly](https://github.com/soutaro/querly) for Ruby program, which is written in Ruby and can add any pattern rules by writing to YAML file.

I'm happy if you consider to add this linter! 😄 

Thanks.

### CODE REVIEW

**Comment by mre** [comment]
Code looks good. At first glance, I couldn't find a license, though. AFAIK, by default, projects without a license are proprietary - even if they are published on Github.

If the above is true, we have two options:
1. We add a `:copyright:` flag to the entry.
2. The projects gets an open source license, which all previous contributors have to sign.

I might be mistaken with those assumptions, though. 😉

**Comment by mre** [comment]
Let's wait until https://github.com/soutaro/querly/pull/44 gets merged.

**Comment by ybiquitous** [comment]
Yeah, I wait too ;)

**Comment by soutaro** [comment]
@mre I just released Querly 0.12.0!

https://rubygems.org/gems/querly/versions/0.12.0

**Comment by mre** [comment]
Thanks all. 🎉

**Pull request merged**
