### PR TITLE
Better handling of tool dicussions

### PR DESCRIPTION
**Pull request by mre**
We recently added guidelines on how to deprecate tools in #224 after a longer discussion in #223.
Since then I have learned a few things the hard way:

1. Discussions can quickly get out of hand. It is not easy (and sometimes impossible) to find a solution that pleases everyone.
2. The role of a project maintainer is to keep collaboration constructive and make all contributors feel welcome.

In light of that, I propose the following changes for contributing:

1. ⚠️ will be replaced with ℹ️. We don't want to spread fear, we want to inform.
2. As far as possible, project maintainers should be involved in the discussion to come to a fair conclusion.
3. Discussions around tools will be linked in the `README.md`.
4. Please remember that we're all human and we all have the same goal of making Open Source a little better.

### CODE REVIEW

**Comment by impredicative** [comment]
I understand the need for a civil discussion, but I fear this is an overreaction. If a tool doesn't support the current version of a language, and there is no hope that it soon will, I would consider its use deprecated. Injecting the tool's author into the discussion is risking a highly biased opinion. I think project maintainers should never be highlighted or called to a discussion. Calling them was the problem.

**Comment by mre** [comment]
I don't see why asking the maintainer if their tool is still maintained is a problem. 
An opinion is always biased but the goal is to reach consensus.
From that perspective, to only way to reach a common ground is to hear all sides.

**Comment by impredicative** [comment]
We saw what happened when opinions from all sides were requested in the prior issue. It didn't help things. This is not a court of law where justice must be served at all costs. I support getting additional less-biased opinions from expert users, however.

**Comment by chadbrewbaker** [comment]
Perhaps tagging tools with language version limitations?  Javascript isn't alone.  Several great C++ linters don't support C++17.

**Comment by mre** [comment]
> Perhaps tagging tools with language version limitations? Javascript isn't alone. Several great C++ linters don't support C++17.

Good point. Maybe there *is* a better way by providing more objective information on the tools. Here's hope that #194 brings more clarity in the future.

**Pull request closed without merging**
