### PR TITLE
Add Security Code Scan

### PR DESCRIPTION
**Pull request by JarLob**

### CODE REVIEW

**Comment by mre** [comment]
Hi @JarLob,
thanks for your contribution. It looks good and I would merge it.
For clarity reasons and to have the same conditions for each tool,
I would prefer to have only one category per tool.
Could we do that?
Which category you choose is up to your liking. Thanks. 🙂

**Comment by JarLob** [comment]
I don’t mind if you clean up other tools that are already in multiple categories. Otherwise I find it unfair :)

**Comment by mre** [comment]
You're right and now that I think of it, from a reader's perspective it might actually make sense to have the same entry multiple times. I assume, most people quickly skim the list for their category and leave again. If a tool fits into multiple categories, there's nothing wrong with that I guess... 🤔

**Comment by JarLob** [comment]
Thanks!

**Pull request merged**
