### PR TITLE
Added pytype to the Python section

### PR DESCRIPTION
**Pull request by uppi**
Added pytype to the Python section

### CODE REVIEW

**Comment by mre** [comment]
Thanks @uppi. Ideally the tools would be sorted alphabetically, but that's no big deal for now. Maybe just a friendly info for next time. I guess I'll merge that and then move pytype up a little. 👍

**Comment by impredicative** [comment]
I consider `pytype` a low-quality tool. Last I tried it, it didn't work, and the author wasn't interested in fixing it.

**Comment by mre** [comment]
Oh! Thanks for the heads-up. So would you propose to remove it again from the list? Don't really have an opinion about it right now. Looking at the recent project activitiy it still seems to be maintained (last commit 14 days ago). Also there is at least one comment to the recent issues.
The documentation is definitely spotty, though.
So in conclusion, if you're for removing it, feel free to do so.

**Comment by impredicative** [comment]
Thanks. To be really fair, I will give it another try, and then remove it only if it really doesn't help me in Python development.

**Pull request merged**
