### PR TITLE
Adding reshift as a new product, released on Nov 2018

### PR DESCRIPTION
**Pull request by qcorporation**

### CODE REVIEW

**Comment by mre** [comment]
Thanks @qcorporation. Could you fix the alphabetical ordering?
Also, the website is redirecting to a login form. Is there a better place for getting initial information about the product that we could use?

**Comment by qcorporation** [comment]
Re: alphabetical ordering - yes definitely
Re: website redirect - yes will link it to the reshift landing page instead

Changes to come.

**Comment by mre** [comment]
Thanks for your changes. The final thing that came to mind is, that redshift seems to be  a webservice. Could we move it to the webservice section? I think that's a better place, given that support for other languages than Java is already on the roadmap. Sorry to bother you again.

**Comment by mre** [comment]
Thanks @qcorporation  :shipit:

**Pull request merged**
