### PR TITLE
Add Semmle QL and LGTM.com, remove discontinued services

### PR DESCRIPTION
**Pull request by sjvs**
This adds Semmle's LGTM.com and QL. Removes various discontinued services: Functor, AttackFlow, BitHound, Node Security Platform.

Let me know if this is not the right way to contribute to this list :slightly_smiling_face:! And feel free to edit the PR directly if needed.

### CODE REVIEW

**Comment by mre** [comment]
Hello @sjvs, nice pull request. 👍 
May I ask you to shorten the description of the new tools a bit? Each description should be no longer than 200 characters.
Apart from that, lgtm. 😉

**Comment by sjvs** [comment]
@mre: no problem! I've shortened the descriptions, they're now both 201 characters. Hope that's all right! Let me know if it needs to be even shorter; I can try to do some more wordsmithing...

**Comment by mre** [comment]
Thanks for the adjustments. The description is still too long by one character, though. 😆 
Usually I'm not that picky, but I'd have to adjust the CI to accept descriptions longer than 200 characters and I don't really want to do that.

Do you think you could strip off one additional character somewhere? Sorry again for the inconvenience.

**Comment by sjvs** [comment]
Ah, I hadn't noticed the automatic CI check for this! Very fancy! I've now removed the links (which I imagine it'll include in the count) and shortened it slightly. Should now be < 200 chars! Fingers crossed...

**Comment by mre** [comment]
lgtm! 
Thanks for your contribution. :shipit:

**Pull request merged**
