### PR TITLE
Add copyright notice to RIPS

### PR DESCRIPTION
**Pull request by Gutem**
RIPS is no longer open source.

### CODE REVIEW

**Comment by JarLob** [comment]
Well there are two versions of RIPS - open-source and the other, commercial. AFAIK the link is to free open source (although [the link to sourceforge](http://rips-scanner.sourceforge.net/) probably is more correct). I think another entry with a link to https://www.ripstech.com/ is needed.

**Comment by Gutem** [comment]
Open source RIPS development is abandoned.
It hasn't OOP support and, if I'm not wrong, only support PHP <= 4.
RIP RIPS (phun intented)

**Comment by JarLob** [comment]
I see your point. But in that case the link has to be changed.

**Comment by mre** [comment]
Yup. @Gutem can you also change the link? I think then we're good.

**Comment by mre** [comment]
Thanks folks! 🎉

**Pull request merged**
