### PR TITLE
Add links to ToC for programming languages

### PR DESCRIPTION
**Pull request by mingrammer**

### CODE REVIEW

**Comment by mre** [comment]
Dunno about that @mingrammer,
it used to be there, but then the table of contents got very long. That's why I removed it in the end. Shall we bring it back? Maybe we find a compromise for subsections or we split the file up into multiple files? 🤔 
I even thought about moving all tools into a YAML file and then letting the CI render a human-readable version and a static HTML version with a JavaScript search.
Open for suggestions. 😉

**Comment by mingrammer** [comment]
Static HTML with search sounds great! URL could be like `awesome-static-analysis.com`.

**Comment by mre** [comment]
It's been a while, but I had some time to set up a fancy static website for this project.
Right now it's here: https://matthias-endler.de/awesome-static-analysis/

Features:
* Super simple setup using [mkdocs](https://www.mkdocs.org/).
* Simply uses the contents of the `README.md` and the logo from the project for content.
* Offers search out of the box.
* Quick, because it's just HTML and some JavaScript.

I'm not happy with the domain yet. Maybe I will change that in the future. If anybody wants to sponsor a URL, ping me. 😉 

Closing this. Hope y'all like it.

**Comment by mgudemann** [comment]
Some entries seem to be missing, e.g., cbmc for c and jbmc for java

Matthias Endler <notifications@github.com> schrieb am Do., 27. Sep. 2018,
18:57:

**Comment by mre** [comment]
Thanks for the hint. Forgot to `git pull`. Should be fixed now.

**Comment by mgudemann** [comment]
Thanks!

Matthias Endler <notifications@github.com> schrieb am Do., 27. Sep. 2018,
20:10:

**Comment by mingrammer** [comment]
Awesome :) !!

**Pull request closed without merging**
