### PR TITLE
Add reference to SPARK for Ada

### PR DESCRIPTION
**Pull request by jklmnn**

### CODE REVIEW

**Comment by mre** [comment]
Hey @jklmnn. Thanks for your contribution. There's just three things:
1. The tools should be alphabetically ordered. Could you fix that?
2. Is the tool distributed under a public license? Otherwise, please add the `:copyright:` tag.
3. Is spark even a tool? 😅

**Comment by jklmnn** [comment]
I have fixed the order and added a copyright tag. While there is a GPL version Adacore also provides [SPARK Pro](https://www.adacore.com/sparkpro) (I actually find this website better than the spark-2014 one but I didn't want to directly refer to the pro version only).

I don't know your exact definition of tool but for me it definitely belongs to this list. It is a subset of Ada (e.g. no access types, pointers for C folks) which brings tools that use Adas aspects to formally verify code. E.g. a precondition that in Ada would cause a runtime error if violated can be used by SPARK to verify that the violation can never occur (generally you can prove the absence of runtime errors).
To be more tool-centric, SPARK comes with `gnatprove` which is the tool that runs the verification (btw. Codepeer that is already in your list is included in SPARK Pro).
Also as far as I know it is the most powerful tool for Ada in this list (if you need more you probably want to use an external prover such as Isabelle or Coq).
I hope this answers 3 ;)

**Comment by mre** [comment]
Looks good now. Thanks! 🏖

**Comment by mre** [comment]
And thanks for the thorough explanation. 👍

**Pull request merged**
